service: serverless-gos3lambda
frameworkVersion: ">=1.28.0"
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::my-bucket/*"

functions:
  api:
    handler: bin/main
    events:
      - http:
          method: GET
          path: /list 

  health:
    handler: bin/main
    events:
      - http:
          method: GET 
          path: /health

  upload:
    handler: bin/main
    events:
     - http:
          method: POST
          path: /upload

package:
  patterns:
    - '!*/**'
    - bin/main
